"""add patient and related tables

Revision ID: f6ad29a9adf1
Revises: 8b3d976291d5
Create Date: 2026-01-12 12:47:26.347527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6ad29a9adf1'
down_revision: Union[str, None] = '8b3d976291d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_facilities',
    sa.Column('facility_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.Enum('hospital', 'clinic', 'pharmacy'), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('healthcare_workers',
    sa.Column('worker_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('facility_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('national_id_encrypted', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('access_logs',
    sa.Column('log_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('accessed_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('facility_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('action', sa.Enum('view', 'edit', 'share'), nullable=False),
    sa.Column('result', sa.Enum('allowed', 'denied'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['accessed_by'], ['healthcare_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('consents',
    sa.Column('consent_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('facility_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('consent_type', sa.Enum('view', 'edit', 'share'), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    op.drop_table('access_logs')
    op.drop_table('patients')
    op.drop_table('healthcare_workers')
    op.drop_table('healthcare_facilities')
    # ### end Alembic commands ###
